# Generated by Django 2.0.2 on 2018-03-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0016_auto_20180303_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='数量')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='books.Book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '购物项',
                'verbose_name_plural': '购物项',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='carts.CartItem', verbose_name='购物项'),
        ),
    ]
