# Generated by Django 2.0.2 on 2018-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180303_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='checked',
            field=models.BooleanField(default=True, verbose_name='选中'),
        ),
    ]
