# Generated by Django 2.0.2 on 2018-03-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_order_item'),
        ('carts', '0004_cartitem_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='users.Order', verbose_name='所属订单'),
        ),
    ]
