# Generated by Django 2.0.2 on 2018-02-28 09:58

import apps.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180228_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/1.jpg', storage=apps.utils.storage.ImageStorage(), upload_to='avatar/%Y/%m', verbose_name='头像'),
        ),
    ]
