# Generated by Django 2.0.2 on 2018-03-04 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_checked'),
        ('users', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], max_length=5, verbose_name='支付方式')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='付款金额')),
                ('paid', models.BooleanField(default=False, verbose_name='已支付')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('state', models.CharField(choices=[('P', '进行'), ('F', '完成')], max_length=5, verbose_name='状态')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='carts.CartItem', verbose_name='图书')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='收货人')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('zip_code', models.CharField(max_length=6, verbose_name='邮编')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name_plural': '收货人信息',
                'verbose_name': '收货人信息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='users.Recipient', verbose_name='收货人信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
