# Generated by Django 2.0.2 on 2018-03-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180304_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='default',
            field=models.BooleanField(default=False, verbose_name='默认'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='manages.Payment', verbose_name='支付方式'),
        ),
    ]
