# Generated by Django 2.0.2 on 2018-02-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180228_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
                ('level', models.CharField(max_length=1, verbose_name='类级')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='books.Category')),
            ],
            options={
                'verbose_name_plural': '分类',
                'verbose_name': '分类',
            },
        ),
    ]
