# Generated by Django 2.0.2 on 2018-02-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='superior',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='books.Category', verbose_name='上级'),
        ),
    ]
