# Generated by Django 2.0.2 on 2018-02-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180228_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
            ],
            options={
                'verbose_name': '一级分类',
                'verbose_name_plural': '一级分类',
            },
        ),
        migrations.CreateModel(
            name='CategorySecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
                ('up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down', to='books.CategoryFirst', verbose_name='上级')),
            ],
            options={
                'verbose_name': '二级分类',
                'verbose_name_plural': '二级分类',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='superior',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
