# Generated by Django 2.0.2 on 2018-02-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180228_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='books.CategorySecond'),
        ),
        migrations.AlterField(
            model_name='categoryfirst',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='类名'),
        ),
        migrations.AlterField(
            model_name='categorysecond',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='类名'),
        ),
    ]
