# Generated by Django 2.0.2 on 2018-02-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180228_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfirst',
            options={'verbose_name': '一级类别', 'verbose_name_plural': '一级类别'},
        ),
        migrations.AlterModelOptions(
            name='categorysecond',
            options={'verbose_name': '二级类别', 'verbose_name_plural': '二级类别'},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='books.CategorySecond', verbose_name='类别'),
        ),
    ]
