# Generated by Django 2.0.2 on 2018-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20180228_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='introduction',
        ),
        migrations.AddField(
            model_name='book',
            name='author_brief',
            field=models.TextField(blank=True, null=True, verbose_name='作者简介'),
        ),
        migrations.AddField(
            model_name='book',
            name='catalog',
            field=models.TextField(blank=True, null=True, verbose_name='目录'),
        ),
        migrations.AddField(
            model_name='book',
            name='content_brief',
            field=models.TextField(blank=True, null=True, verbose_name='内容简介'),
        ),
    ]
