# Generated by Django 2.0.2 on 2018-03-03 16:43

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20180302_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_brief',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='作者简介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_brief',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容简介'),
        ),
    ]
