# Generated by Django 2.0.2 on 2018-03-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], max_length=5)),
            ],
        ),
    ]
