# Generated by Django 2.0.2 on 2018-03-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0003_auto_20180305_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], max_length=10, verbose_name='名称'),
        ),
    ]
